
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'left+-left*/FLOORDIV%rightUMINUSFLOOR FLOORDIV NAME NUMBER REALstatement : NAME "=" expression\n| REAL "=" expression\n| FLOOR "=" expressionstatement : expressionexpression : expression \'+\' expression\n| expression \'-\' expression\n| expression \'*\' expression\n| expression \'/\' expression\n| expression FLOORDIV expression\n| expression \'%\' expressionexpression : \'-\' expression %prec UMINUSexpression : \'(\' expression \')\'expression : REAL \'(\' expression \')\'expression : FLOOR \'(\' expression \')\'expression : NUMBERexpression : NAME\n| REAL\n| FLOOR'
    
_lr_action_items = {'NAME':([0,6,7,9,10,11,12,13,14,15,16,17,18,19,],[2,23,23,23,23,23,23,23,23,23,23,23,23,23,]),'REAL':([0,6,7,9,10,11,12,13,14,15,16,17,18,19,],[4,21,21,21,21,21,21,21,21,21,21,21,21,21,]),'FLOOR':([0,6,7,9,10,11,12,13,14,15,16,17,18,19,],[5,22,22,22,22,22,22,22,22,22,22,22,22,22,]),'-':([0,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[6,-16,11,-17,-18,6,6,-15,6,6,6,6,6,6,6,6,6,6,6,-11,-17,-18,-16,11,11,-5,-6,-7,-8,-9,-10,11,11,11,11,-12,-13,-14,]),'(':([0,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,21,22,],[7,17,19,7,7,7,7,7,7,7,7,7,7,7,7,7,17,19,]),'NUMBER':([0,6,7,9,10,11,12,13,14,15,16,17,18,19,],[8,8,8,8,8,8,8,8,8,8,8,8,8,8,]),'$end':([1,2,3,4,5,8,20,21,22,23,25,26,27,28,29,30,31,32,34,36,37,38,],[0,-16,-4,-17,-18,-15,-11,-17,-18,-16,-1,-5,-6,-7,-8,-9,-10,-2,-3,-12,-13,-14,]),'=':([2,4,5,],[9,16,18,]),'+':([2,3,4,5,8,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[-16,10,-17,-18,-15,-11,-17,-18,-16,10,10,-5,-6,-7,-8,-9,-10,10,10,10,10,-12,-13,-14,]),'*':([2,3,4,5,8,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[-16,12,-17,-18,-15,-11,-17,-18,-16,12,12,12,12,-7,-8,-9,-10,12,12,12,12,-12,-13,-14,]),'/':([2,3,4,5,8,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[-16,13,-17,-18,-15,-11,-17,-18,-16,13,13,13,13,-7,-8,-9,-10,13,13,13,13,-12,-13,-14,]),'FLOORDIV':([2,3,4,5,8,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[-16,14,-17,-18,-15,-11,-17,-18,-16,14,14,14,14,-7,-8,-9,-10,14,14,14,14,-12,-13,-14,]),'%':([2,3,4,5,8,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,],[-16,15,-17,-18,-15,-11,-17,-18,-16,15,15,15,15,-7,-8,-9,-10,15,15,15,15,-12,-13,-14,]),')':([8,20,21,22,23,24,26,27,28,29,30,31,33,35,36,37,38,],[-15,-11,-17,-18,-16,36,-5,-6,-7,-8,-9,-10,37,38,-12,-13,-14,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,6,7,9,10,11,12,13,14,15,16,17,18,19,],[3,20,24,25,26,27,28,29,30,31,32,33,34,35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME = expression','statement',3,'p_statement_assign','calc.py',80),
  ('statement -> REAL = expression','statement',3,'p_statement_assign','calc.py',81),
  ('statement -> FLOOR = expression','statement',3,'p_statement_assign','calc.py',82),
  ('statement -> expression','statement',1,'p_statement_expr','calc.py',87),
  ('expression -> expression + expression','expression',3,'p_expression_binop','calc.py',92),
  ('expression -> expression - expression','expression',3,'p_expression_binop','calc.py',93),
  ('expression -> expression * expression','expression',3,'p_expression_binop','calc.py',94),
  ('expression -> expression / expression','expression',3,'p_expression_binop','calc.py',95),
  ('expression -> expression FLOORDIV expression','expression',3,'p_expression_binop','calc.py',96),
  ('expression -> expression % expression','expression',3,'p_expression_binop','calc.py',97),
  ('expression -> - expression','expression',2,'p_expression_uminus','calc.py',122),
  ('expression -> ( expression )','expression',3,'p_expression_group','calc.py',127),
  ('expression -> REAL ( expression )','expression',4,'p_expression_real','calc.py',132),
  ('expression -> FLOOR ( expression )','expression',4,'p_expression_floor','calc.py',137),
  ('expression -> NUMBER','expression',1,'p_expression_number','calc.py',142),
  ('expression -> NAME','expression',1,'p_expression_name','calc.py',147),
  ('expression -> REAL','expression',1,'p_expression_name','calc.py',148),
  ('expression -> FLOOR','expression',1,'p_expression_name','calc.py',149),
]
