
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'left+-left*/FLOORDIV%rightUMINUSFLOORDIV NAME NUMBER REALstatement : NAME "=" expressionstatement : expressionexpression : expression \'+\' expression\n| expression \'-\' expression\n| expression \'*\' expression\n| expression \'/\' expression\n| expression FLOORDIV expression\n| expression \'%\' expressionexpression : \'-\' expression %prec UMINUSexpression : \'(\' expression \')\'expression : REAL \'(\' expression \')\'expression : NUMBERexpression : NAME'
    
_lr_action_items = {'NAME':([0,4,5,8,9,10,11,12,13,14,18,],[2,16,16,16,16,16,16,16,16,16,16,]),'-':([0,2,3,4,5,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,],[4,-13,10,4,4,-12,4,4,4,4,4,4,4,-9,-13,10,4,10,-3,-4,-5,-6,-7,-8,-10,10,-11,]),'(':([0,4,5,6,8,9,10,11,12,13,14,18,],[5,5,5,18,5,5,5,5,5,5,5,5,]),'REAL':([0,4,5,8,9,10,11,12,13,14,18,],[6,6,6,6,6,6,6,6,6,6,6,]),'NUMBER':([0,4,5,8,9,10,11,12,13,14,18,],[7,7,7,7,7,7,7,7,7,7,7,]),'$end':([1,2,3,7,15,16,19,20,21,22,23,24,25,26,28,],[0,-13,-2,-12,-9,-13,-1,-3,-4,-5,-6,-7,-8,-10,-11,]),'=':([2,],[8,]),'+':([2,3,7,15,16,17,19,20,21,22,23,24,25,26,27,28,],[-13,9,-12,-9,-13,9,9,-3,-4,-5,-6,-7,-8,-10,9,-11,]),'*':([2,3,7,15,16,17,19,20,21,22,23,24,25,26,27,28,],[-13,11,-12,-9,-13,11,11,11,11,-5,-6,-7,-8,-10,11,-11,]),'/':([2,3,7,15,16,17,19,20,21,22,23,24,25,26,27,28,],[-13,12,-12,-9,-13,12,12,12,12,-5,-6,-7,-8,-10,12,-11,]),'FLOORDIV':([2,3,7,15,16,17,19,20,21,22,23,24,25,26,27,28,],[-13,13,-12,-9,-13,13,13,13,13,-5,-6,-7,-8,-10,13,-11,]),'%':([2,3,7,15,16,17,19,20,21,22,23,24,25,26,27,28,],[-13,14,-12,-9,-13,14,14,14,14,-5,-6,-7,-8,-10,14,-11,]),')':([7,15,16,17,20,21,22,23,24,25,26,27,28,],[-12,-9,-13,26,-3,-4,-5,-6,-7,-8,-10,28,-11,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([0,4,5,8,9,10,11,12,13,14,18,],[3,15,17,19,20,21,22,23,24,25,27,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> NAME = expression','statement',3,'p_statement_assign','calc.py',62),
  ('statement -> expression','statement',1,'p_statement_expr','calc.py',67),
  ('expression -> expression + expression','expression',3,'p_expression_binop','calc.py',72),
  ('expression -> expression - expression','expression',3,'p_expression_binop','calc.py',73),
  ('expression -> expression * expression','expression',3,'p_expression_binop','calc.py',74),
  ('expression -> expression / expression','expression',3,'p_expression_binop','calc.py',75),
  ('expression -> expression FLOORDIV expression','expression',3,'p_expression_binop','calc.py',76),
  ('expression -> expression % expression','expression',3,'p_expression_binop','calc.py',77),
  ('expression -> - expression','expression',2,'p_expression_uminus','calc.py',94),
  ('expression -> ( expression )','expression',3,'p_expression_group','calc.py',99),
  ('expression -> REAL ( expression )','expression',4,'p_expression_real','calc.py',104),
  ('expression -> NUMBER','expression',1,'p_expression_number','calc.py',109),
  ('expression -> NAME','expression',1,'p_expression_name','calc.py',114),
]
